### PR TITLE
Create CEVNI_MapCSS.mapcss

### PR DESCRIPTION
**Pull request by Dirk--**
notice_a10a
notice_a10b
notice_a12
notice_a13
notice_a14
notice_a15
notice_a16
notice_a17
notice_a18
notice_a19
notice_a20
notice_b1a
notice_b1b
notice_b2a
notice_b2b
notice_b3a
notice_b3b
notice_b4a
notice_b4b
notice_b5
notice_b6
notice_b7
notice_b8
notice_b9a
notice_b9b
notice_b11
notice_c1
notice_c2
notice_c3
notice_c4
notice_c5a
notice_c5b
notice_d1a
notice_d1b
notice_d2a
notice_d2b
notice_d3a
notice_d3b
notice_e1
notice_e2
notice_e3
notice_e4a
notice_e4b
notice_e5 1
notice_e5 2
notice_e5 3
notice_e5 4
notice_e5 5
notice_e5 6
notice_e5 7
notice_e5 8
notice_e5 9
notice_e5 10
notice_e5 11
notice_e5 12
notice_e5 13
notice_e5 14
notice_e5 15
notice_e5
notice_e6
notice_e7 1
notice_e7
notice_e8
notice_e9a
notice_e9b
notice_e9c
notice_e9d
notice_e9e
notice_e9f
notice_e9g
notice_e9h
notice_e9i
notice_e10a
notice_e10b
notice_e10c
notice_e10d
notice_e10e
notice_e10f
notice_e11
notice_e13
notice_e14
notice_e15
notice_e16
notice_e17
notice_e18
notice_e19
notice_e20
notice_e21
notice_e22
notice_e23
notice_e24
notice_right_triangle
notice_left_triangle
notice_bottom_triangle
notice_board
notice_a1
notice_a1a
notice_a2
notice_a3
notice_a4 1
notice_a4
notice_a5 1
notice_a5
notice_a6
notice_a7
notice_a8
notice_a9

### CODE REVIEW

**Comment by Dirk--** [comment]
Thanks Malcolm, but how do I get these icons in place (OpenSeaMap/josm/icons/png/...) ?

**Comment by malcolmh** [comment]
You will have to add rules to the MapCSS file. Aun should be able to help you with this.

**Comment by malcolmh** [comment]
Oh - I see that you have already made your own MapCSS file. You need to install it in JOSM. Preferences->Map Settings->Tagging Presets: Click "+" on right box and enter your file details.

**Comment by Skippern** [comment]
I would prefere if it could be amended to the general seamarks mapcss I am working on instead of as a separate set of rules. There is already a CEVNI section there, but since I have not had much time for it, only main boards are displayed

Aun Johnsen

**Comment by Dirk--** [comment]
@malcolmh : I do know how to  install this in JOSM, the style just depends on the pngs so I need to know how to at them here in the github repro ...
@Skippern : I see advantages in a modular concept, eg. having BNIWR and PPWBC notice marks in separate files, too.

**Comment by malcolmh** [comment]
Look at Aun's MapCSS source to see how icons are accessed from the repository.

**Comment by Dirk--** [comment]
sorry for causing this confusion ;-) 
I need to know how to <b>upload/add</b> icons to this repository...

**Comment by malcolmh** [comment]
I assume that what you are asking for is the ability to merge pull requests in this repository?

If so, post a request for this in the openseamap-dev mailing list so that whoever the admins will hopefully respond.

**Comment by Skippern** [comment]
@Dirk-- All the icons you need are already in the repo as SVN files

**Comment by Dirk--** [comment]
Hi Aun, can not find any CEVNI notemarks at josm/icons/svg/ ...

**Comment by malcolmh** [comment]
josm/icons/svg/Q/Q126/CEVNI/

**Comment by Skippern** [comment]
Thanks @malcolmh Didn’t have time to look it up and didn’t remember exactly which subfolder

Aun Johnsen

**Comment by Dirk--** [comment]
Thanks, this should work. Where do I find
- left_triangle
- right_triangle
- bottom_triangle
- bottom_board
- top_board
?

**Comment by Skippern** [comment]
Ah,

Sidebords, topboard and bottom boards not included, if you can create them in SVG and make a PR I’ll make sure they end up in the right place

Aun Johnsen

**Comment by malcolmh** [comment]
Take a look in:renderer/tree/master/searender/symbols/symbols.defs. These are all the SVGs that are used in the current renderer. Look for "notice_board" and "notice_triangle". You will have to embed those symbol definitions in a full SVG wrapper and re-scale to suit.

**Comment by Skippern** [comment]
Is there a point of copying them to this repo?
Aun Johnsen

**Comment by malcolmh** [comment]
For compatibility reasons. They are not stand-alone SVG files, are doubtless the wrong size, and in the case of the triangle, will need three different rotations for each of the cases.

**Comment by Skippern** [comment]
I think we should make a proper copy of them for this repo, I’ll put it on my TODO list if nobody beat me to it
Aun Johnsen

**Comment by Dirk--** [comment]
@Skippern: Yes, please add those boards (I still do not know how to add icons to this repository)

**Comment by Skippern** [comment]
Dirk if you have them as working SVG you can just pull them, and I’ll sort them out and place them in the right folder, or if you want me to process them you’ll have to wait for my schedule to give me the time.

If you have problems creating a pull request you can also mail me the files directly and I’ll pull them in for you

Aun Johnsen

**Pull request merged**
